import type { NoteKind } from '../data/investigation.ts'

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`

export const flow = {
  stepOf: (n: number) => `Step ${n} of 4`,
  steps: ['Place', 'Outline', 'Dates', 'Review'],
  place: {
    title: 'Where is it?',
    chosen: (name: string) => `Chosen: ${name}`,
    need: 'Search for a place or paste coordinates to continue.',
  },
  outline: {
    title: 'What are we looking at?',
    kindLegend: 'Kind of place',
    site: 'A building or site',
    siteHelp: 'Draw around the whole site.',
    road: 'A road',
    roadHelp: 'Draw along the centre of the road.',
    width: 'Road width (metres)',
    widthHelp: 'Full width including shoulders, 5 to 200. It decides which pixels count as road.',
    drawSite: 'Click on the map to place corners. Click the first corner again to finish.',
    drawRoad: 'Click along the road. Click the last point again to finish.',
    redraw: 'Draw again',
    byCoords: 'Enter by coordinates instead',
    centre: 'Centre (lat, lon)',
    side: 'Square side (metres)',
    sideHelp: 'From 100 to 3000 metres.',
    useSquare: 'Use this square',
    start: 'Start point (lat, lon)',
    end: 'End point (lat, lon)',
    useLine: 'Use this line',
    badPoint: 'Enter coordinates like 21.1458, 79.0882.',
    summarySite: (km2: number, km: number) => `Area ${km2.toFixed(2)} km² · ${km.toFixed(2)} km across`,
    summaryRoad: (km: number, n: number) =>
      `Length ${km.toFixed(2)} km · ${plural(n, 'section', 'sections')} of up to 2 km`,
    none: 'No outline yet.',
  },
  dates: {
    title: 'Which dates?',
    from: 'From',
    to: 'To',
    help: 'Photos exist from 2017. Shorter ranges load faster.',
    order: 'The start date must be before the end date.',
    early: 'Photos start in 2017. Choose 1 Jan 2017 or later.',
    future: 'The end date cannot be in the future.',
    estimate: (dates: number, mb: number) =>
      `About ${dates} satellite passes. The first view uses about ${mb} MB of data.`,
  },
  review: {
    title: 'Review',
    name: 'Name',
    open: 'Open the workbench',
    privacy:
      'Nothing is uploaded. Photos are read from public Sentinel-2 files, and your outline stays in this browser until you choose to save.',
    kind: { site: 'Site', road: 'Road' },
    range: (from: string, to: string) => `${from} to ${to}`,
    labels: { kind: 'Kind', size: 'Size', dates: 'Dates', data: 'Data' },
  },
  workbench: {
    searching: 'Finding satellite passes',
    searchingMore: 'Finding the other passes.',
    none: 'No Sentinel-2 photos cover this outline in these dates. Try a longer date range.',
    allCloudy:
      'Every photo in these dates is obscured or does not cover your outline. Try other dates. Your notes are kept.',
    searchFailed: 'Could not reach the satellite catalogue. Check your connection and try again.',
    limited: 'Some passes are not shown. Narrow the dates to see them all.',
    catalogueNote: 'The catalogue may omit a few passes.',
    before: 'Before',
    after: 'After',
    pickPair: 'Pick a clear "before" and "after" date on the timeline.',
    notEnoughClear: 'Only one photo in these dates is clear enough to compare. Try a longer date range.',
    view: 'View',
    modes: { swipe: 'Swipe', side: 'Side by side', diff: 'Difference' },
    swipeLabel: 'Reveal the after photo',
    outlineToggle: 'Show outline',
    diffCaption:
      'Brightness difference between these two dates. Season, moisture, shadows and clouds also cause differences. This is not a construction detector.',
    caption: (date: string, clearPct?: number) =>
      `${date} · Sentinel-2 · 10 m${clearPct === undefined ? '' : ` · ${clearPct}% clear view`}`,
    photoAlt: (role: string, date: string, clearPct?: number) =>
      `${role} photo, ${date}, Sentinel-2 true colour${clearPct !== undefined ? ` · ${clearPct}% clear view` : ''}`,
    timeline: 'Timeline',
    timelineLabel: 'Satellite pass',
    passes: (n: number) => plural(n, 'pass', 'passes'),
    useBefore: 'Use as before',
    useAfter: 'Use as after',
    pin: 'Pin to report',
    unpin: 'Unpin',
    pinLimit: 'You can pin up to 24 dates.',
    legend: 'Each mark shows how clearly that photo sees your outline.',
    grid: 'Sections × dates',
    sectionCol: 'Section',
    section: (from: number, to: number) => `${(from / 1000).toFixed(1)}–${(to / 1000).toFixed(1)} km`,
    shares: {
      valid: 'Visible ground',
      uncertain: 'Uncertain (shadow or unclassified)',
      obstructed: 'Obscured (cloud, shadow, snow)',
      nodata: 'No data',
    },
    cell: (section: string, date: string, word: string) => `${section}, ${date}: ${word}`,
    showMap: 'Show map',
    hideMap: 'Hide map',
    report: 'Report',
    notSaved: 'Not saved',
    meta: {
      site: (km2: number, dates: string) => `Site · ${km2.toFixed(2)} km² · ${dates}`,
      road: (km: number, widthM: number, dates: string) =>
        `Road · ${km.toFixed(1)} km · ${widthM} m wide · ${dates}`,
      pair: (before: string, after: string) => `${before} ↔ ${after}`,
    },
    loadingPhoto: 'Loading photo',
    checkFailed: 'This photo could not be checked.',
    badOutline: 'This outline can no longer be read. Draw it again from the start.',
    thumbFailed: 'Preview unavailable.',
    notFound:
      'This investigation is not in this browser. It may have been deleted, or saved on another device.',
    disclaimer: '"No clear visible change" does not prove that nothing happened. Roofs hide interiors.',
    errors: {
      BAD_ORDER: 'The before date must be earlier than the after date.',
      TOO_MANY_PINS: 'You can pin up to 24 dates.',
      NOTE_EMPTY: 'Write what you see before adding the note.',
      NOTE_TOO_LONG: 'Notes can be up to 2000 characters.',
      TOO_MANY_NOTES: 'An investigation can hold up to 200 notes.',
      CLAIM_TOO_LONG: 'The claim is too long.',
      STORE_FAILED: "Could not load this investigation from your browser's storage.",
      SAVE_FAILED: 'Could not save your changes. Try again.',
    } as Record<string, string>,
  },
  notes: {
    title: 'Notes',
    what: 'What do you see?',
    kindLegend: 'Your reading',
    kinds: {
      change: 'Visible change',
      no_clear_change: 'No clear visible change',
      unsure: 'Not sure',
    } satisfies Record<NoteKind, string>,
    forDate: 'Photo date',
    anyDate: 'No specific date',
    forSection: 'Section',
    anySection: 'Whole road',
    add: 'Add note',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    deleted: 'Note deleted.',
    undo: 'Undo',
    count: (n: number) => `${n} / 2000`,
    none: 'No notes yet.',
  },
  claim: {
    title: 'Claim (optional)',
    help: 'A statement you want to compare with the photos, for example "Road surface laid by June 2025". GrahSaboot shows it next to the evidence and does not judge it.',
    text: 'Claim',
    date: 'Claimed date',
    criterion: 'What would be visible from above if it were true?',
    save: 'Save claim',
    remove: 'Remove claim',
  },
  report: {
    title: 'Evidence report',
    preparing: 'Preparing the report',
    needPair: 'Choose a before and an after date in the workbench first. The report is built from them.',
    preparedBy: 'Prepared by (optional)',
    download: 'Download HTML',
    provenance: 'Download provenance JSON',
    print: 'Print or save as PDF',
    back: 'Back to the workbench',
    sections: {
      looked: 'What was looked at',
      evidence: 'Evidence',
      timeline: 'Pinned dates',
      grid: 'Sections × dates',
      notes: 'Notes',
      claim: 'Claim',
      gaps: 'Gaps and limits',
      provenance: 'Provenance',
      attribution: 'Attribution',
    },
    generated: 'Generated',
    unverified:
      'Not verified. This investigation is not saved. The pictures were derived in a browser from the public Sentinel-2 files listed in the provenance.',
    noNotes: 'No notes.',
    noClaim: 'No claim was entered.',
    obscured: (n: number, total: number) => `${n} of ${total} pinned dates are obscured or not covered.`,
    nativeNote: 'Source pixels exactly as hashed (native 10 m grid, before reprojection).',
  },
}
